version: '3.8'

services:
  web:
    build: ./crawling_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./crawling_site/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on: 
      - db

  # celery:
  #   build: ./crawling_site
  #   command: celery --app=crawling_site worker --loglevel=info
  #   volumes:
  #     - ./crawling_site/:/usr/src/app/
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - web
  #     - redis

  # celery-beat:
  #   build: ./crawling_site
  #   command: celery -A crawling_site beat -l info
  #   volumes:
  #     - ./crawling_site/:/usr/src/app/
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - redis

  # dashboard:
  #   build: ./crawling_site
  #   command:  flower -A crawling_site --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - 5555:5555
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - web
  #     - redis
  #     - celery

  # redis:
  #   image: redis:5-alpine

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 80:80

volumes:
  postgres_data: