# Generated by Django 3.1.5 on 2021-01-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=200)),
                ('member_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(default='제목 넣어줘..', max_length=100)),
                ('question_number', models.CharField(default='번호 넣어줘..', max_length=100)),
                ('question_tier', models.CharField(choices=[('B5', 'Bronze V'), ('B4', 'Bronze IV'), ('B3', 'Bronze III'), ('B2', 'Bronze II'), ('B1', 'Bronze I'), ('S5', 'Silver V'), ('S4', 'Silver IV'), ('S3', 'Silver III'), ('S2', 'Silver II'), ('S1', 'Silver I'), ('G5', 'Gold V'), ('G4', 'Gold IV'), ('G3', 'Gold III'), ('G2', 'Gold II'), ('G1', 'Gold I'), ('P5', 'Platinum V'), ('P4', 'Platinum IV'), ('P3', 'Platinum III'), ('P2', 'Platinum II'), ('P1', 'Platinum I'), ('D5', 'Diamond V'), ('D4', 'Diamond IV'), ('D3', 'Diamond III'), ('D2', 'Diamond II'), ('D1', 'Diamond I'), ('R5', 'Ruby V'), ('R4', 'Ruby IV'), ('R3', 'Ruby III'), ('R2', 'Ruby II'), ('R1', 'Ruby I'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='B5', max_length=200)),
                ('question_site', models.CharField(choices=[('B', 'Baekjoon'), ('L', 'Leetcode')], default='B', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_day', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_crawl_info.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_crawl_info.question')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='member_solves',
            field=models.ManyToManyField(through='show_crawl_info.Solve', to='show_crawl_info.Question'),
        ),
    ]
