# Generated by Django 3.1.5 on 2021-01-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_tier',
            field=models.CharField(choices=[('Bronze V', 'Bronze V'), ('Bronze IV', 'Bronze IV'), ('Bronze III', 'Bronze III'), ('Bronze II', 'Bronze II'), ('Bronze I', 'Bronze I'), ('Silver V', 'Silver V'), ('Silver IV', 'Silver IV'), ('Silver III', 'Silver III'), ('Silver II', 'Silver II'), ('Silver I', 'Silver I'), ('Gold V', 'Gold V'), ('Gold IV', 'Gold IV'), ('Gold III', 'Gold III'), ('Gold II', 'Gold II'), ('Gold I', 'Gold I'), ('Platinum V', 'Platinum V'), ('Platinum IV', 'Platinum IV'), ('Platinum III', 'Platinum III'), ('Platinum II', 'Platinum II'), ('Platinum I', 'Platinum I'), ('Diamond V', 'Diamond V'), ('Diamond IV', 'Diamond IV'), ('Diamond III', 'Diamond III'), ('Diamond II', 'Diamond II'), ('Diamond I', 'Diamond I'), ('Ruby V', 'Ruby V'), ('Ruby IV', 'Ruby IV'), ('Ruby III', 'Ruby III'), ('Ruby II', 'Ruby II'), ('Ruby I', 'Ruby I'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='B5', max_length=200),
        ),
    ]
