# Generated by Django 3.1.5 on 2021-01-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0002_auto_20210130_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solve',
            old_name='solved_day',
            new_name='solved_time',
        ),
    ]
