# Generated by Django 3.1.5 on 2021-01-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0003_auto_20210129_2224'),
    ]

    operations = [
    ]
