# Generated by Django 3.1.5 on 2021-01-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0004_auto_20210129_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_tier',
            field=models.CharField(choices=[('B5', 'Bronze 5'), ('B4', 'Bronze 4'), ('B3', 'Bronze 3'), ('B2', 'Bronze 2'), ('B1', 'Bronze 1'), ('S5', 'Silver 5'), ('S4', 'Silver 4'), ('S3', 'Silver 3'), ('S2', 'Silver 2'), ('S1', 'Silver 1'), ('G5', 'Gold 5'), ('G4', 'Gold 4'), ('G3', 'Gold 3'), ('G2', 'Gold 2'), ('G1', 'Gold 1'), ('P5', 'Platinum 5'), ('P4', 'Platinum 4'), ('P3', 'Platinum 3'), ('P2', 'Platinum 2'), ('P1', 'Platinum 1'), ('D5', 'Diamond 5'), ('D4', 'Diamond 4'), ('D3', 'Diamond 3'), ('D2', 'Diamond 2'), ('D1', 'Diamond 1'), ('R5', 'Ruby 5'), ('R4', 'Ruby 4'), ('R3', 'Ruby 3'), ('R2', 'Ruby 2'), ('R1', 'Ruby 1'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='B5', max_length=200),
        ),
    ]
