# Generated by Django 3.1.5 on 2021-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0005_auto_20210205_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
