# Generated by Django 3.1.5 on 2021-01-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0005_auto_20210129_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='show_crawl_info.member')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='show_crawl_info.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='member',
            field=models.ManyToManyField(through='show_crawl_info.QuestionMember', to='show_crawl_info.Member'),
        ),
    ]
