# Generated by Django 3.1.5 on 2021-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0006_update_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update_time',
            options={'ordering': ['-updated_time']},
        ),
        migrations.AddField(
            model_name='update_time',
            name='updater',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='update_time',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
