# Generated by Django 3.1.5 on 2021-01-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0006_auto_20210129_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='member',
        ),
        migrations.AddField(
            model_name='question',
            name='question_solver',
            field=models.ManyToManyField(to='show_crawl_info.Member'),
        ),
        migrations.DeleteModel(
            name='QuestionMember',
        ),
    ]
