# Generated by Django 3.1.5 on 2021-01-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_crawl_info', '0007_auto_20210129_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_solver',
        ),
        migrations.AddField(
            model_name='member',
            name='member_solved',
            field=models.ManyToManyField(to='show_crawl_info.Question'),
        ),
    ]
